oro_frontend:
    frontend_api:
        cors:
            allow_origins:
                - 'http://localhost:3000'
                - 'https://oro-headless.loca.lt'
oro_api:
    cors:
        allow_origins:
            - 'http://localhost:3000'
            - 'https://oro-headless.loca.lt'

oro_oauth2_server:
    authorization_server:
        access_token_lifetime: 36000
        cors:
            allow_origins:
                - 'http://localhost:3000'
                - 'https://oro-headless.loca.lt'